custom:
  - 'https://mempool.space/address/bc1qcrj9wreunffxm75fcz0a2gjkw87jshcwvmxv68'
  - 'https://etherscan.io/address/0xB85Bf389E5fC5E12636FB6F17b68Df7fC990a3dA'
  - 'https://blockchair.com/litecoin/address/ltc1q0nsarncmnz8vk34dav7l0vgu9m5k48drr8z6js'
  - 'https://blockchair.com/dogecoin/address/D6YGoYWpFZxW8JXvEfT5iB9uNXcs8AeY7L'
